apiVersion: apps/v1
kind: Deployment
metadata:
  name: exhort-cve-service
  labels:
    app: exhort-cve-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exhort-cve-service
  template:
    metadata:
      labels:
        app: exhort-cve-service
    spec:
      containers:
      - name: exhort-cve-service
        image: exhort-cve-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DB_REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: exhort-cve-secret
                key: db.endpoint
          - name: DB_REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: exhort-cve-secret
                key: db.port
          - name: API_NVD_APIKEY
            valueFrom:
              secretKeyRef:
                name: exhort-cve-secret
                key: api-nvd-apikey
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 9000
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: exhort-cve-service
  labels:
    app: exhort-cve-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: exhort-cve-service
